obj-y += standby.o
obj-y += standby_dram_crc.o
obj-y += wakeup_source.o
obj-$(CFG_SUN50IW10P1) += standby-sun50iw10p1/
obj-$(CFG_SUN50IW12P1) += standby-sun50iw12p1/
obj-$(CFG_SUN55IW3P1) += standby-sun55iw3p1/
obj-$(CFG_SUN60IW1P1) += standby-sun60iw1p1/
