#ifndef _OPTEE_H
#define _OPTEE_H

#define REGULATOR_NUM                   (20)            /* the number of regulator */
#define PMU_NUM                         (4)             /* the number of pmu */

typedef unsigned int u32;
typedef unsigned short u16;

typedef enum power_dm {
	DM_CPUA = 0,		/* 0  */
	DM_CPUB,		/* 1  */
	DM_DRAM,		/* 2  */
	DM_GPU,			/* 3  */
	DM_SYS,			/* 4  */
	DM_VPU,			/* 5  */
	DM_CPUS,		/* 6  */
	DM_DRAMPLL,		/* 7  */
	DM_ADC,			/* 8  */
	DM_PL,			/* 9  */
	DM_PM,			/* 10 */
	DM_IO,			/* 11 */
	DM_CPVDD,		/* 12 */
	DM_LDOIN,		/* 13 */
	DM_PLL,			/* 14 */
	DM_LPDDR,		/* 15 */
	DM_TEST,		/* 16 */
	DM_RES1,		/* 17 */
	DM_RES2,		/* 18 */
	DM_RES3,		/* 19 */
	DM_MAX,			/* 20 */
} power_dm_e;

typedef enum VDD_BIT {
	VDD_CPUA_BIT = 0,
	VDD_CPUB_BIT,
	VCC_DRAM_BIT,
	VDD_GPU_BIT,
	VDD_SYS_BIT,
	VDD_VPU_BIT,
	VDD_CPUS_BIT,
	VDD_DRAMPLL_BIT,
	VCC_ADC_BIT,
	VCC_PL_BIT,
	VCC_PM_BIT,
	VCC_IO_BIT,
	VCC_CPVDD_BIT,
	VCC_LDOIN_BIT,
	VCC_PLL_BIT,
	VCC_LPDDR_BIT,
	VDD_TEST_BIT,
	VDD_RES1_BIT,
	VDD_RES2_BIT,
	VDD_RES3_BIT,
	VCC_MAX_INDEX,
} VDD_BIT_e;

typedef struct bitmap_name_mapping {
	unsigned int mask_bit;
	char id_name[20];
} bitmap_name_mapping_t;

typedef struct pmu_dts_para {
	unsigned int vdd_cpua;
	unsigned int vdd_cpub;
	unsigned int vdd_sys;
	unsigned int vcc_pll;
	unsigned int vcc_io;
	unsigned int vdd_res1;
	unsigned int vdd_res2;
	unsigned int pmu_count;
	unsigned int pmu_port;
	unsigned int pmu_para;
	unsigned char pmu_id[PMU_NUM];
	unsigned char pmu_addr[PMU_NUM];
} pmu_dts_para_t;

typedef struct spare_boot_ctrl_head {
	unsigned int  jump_instruction;   /* one intruction jumping to real code */
	unsigned char magic[8];           /* ="optee"                            */
	unsigned int  dram_size;          /* generated by PC                     */
	unsigned int  drm_size;	          /* align size in byte                  */
	unsigned int  length;             /* the size of all file                */
	unsigned int  optee_length;       /* the size of optee                   */
	unsigned char version[8];         /* optee version                       */
	unsigned char platform[8];        /* platform information                */
	int           dram_para[32];        /* stamp space, 16bytes align          */
	unsigned char expand_magic[8];      /* ="expand" or null                 */
	unsigned char expand_version[8];    /* expand version                    */
	unsigned int vdd_cpua;
	unsigned int vdd_cpub;
	unsigned int vdd_sys;
	unsigned int vcc_pll;
	unsigned int vcc_io;
	unsigned int vdd_res1;
	unsigned int vdd_res2;
	unsigned int pmu_count;
	unsigned int pmu_port;
	unsigned int pmu_para;
	unsigned char pmu_id[PMU_NUM];
	unsigned char pmu_addr[PMU_NUM];
} spare_boot_ctrl_head_t;

#endif /* _OPTEE_H */
