BINARY = 2977f028-30d8-478b-975c-beeb3c134c34
include $(DEV_KIT_DIR)/../platform_config.mk
# Note that it is important that that $(BINARY) is set before we include
# ta_dev_kit.mk.
include $(TA_DEV_KIT_DIR)/mk/ta_dev_kit.mk
