LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := iwnpi
LOCAL_MODULE_OWNER := unisoc
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_SRC_FILES := iwnpi
LOCAL_CHECK_ELF_FILES := false
LOCAL_PROPRIETARY_MODULE := true
include $(BUILD_PREBUILT)
