obj-y += cpu/

obj-$(CFG_SUN50IW6P1) += plat-sun50iw6p1/
CFLAGS-$(CFG_SUN50IW6P1) += -Iarch/openrisc/plat-sun50iw6p1/inc
CFLAGS-$(CFG_SUN50IW6P1) += -Iservice/standby/suspend_resume/mem-sun50iw6p1/
#LINK-$(CFG_SUN50IW6P1) := coco/arch/openrisc/plat-sun50iw6p1/kern.ld.S
LINK_RAM-$(CFG_SUN50IW6P1) := arch/openrisc/plat-sun50iw6p1/ram.ld

obj-$(CFG_SUN50IW10P1) += plat-sun50iw10p1/
CFLAGS-$(CFG_SUN50IW10P1) += -Iarch/openrisc/plat-sun50iw10p1/inc
CFLAGS-$(CFG_SUN50IW10P1) += -Iservice/standby/suspend_resume/mem-sun50iw10p1/
#LINK-$(CFG_SUN50IW10P1) := coco/arch/openrisc/plat-sun50iw10p1/kern.ld.S
LINK_RAM-$(CFG_SUN50IW10P1) := arch/openrisc/plat-sun50iw10p1/ram.ld

obj-$(CFG_SUN50IW12P1) += plat-sun50iw12p1/
CFLAGS-$(CFG_SUN50IW12P1) += -Iarch/openrisc/plat-sun50iw12p1/inc
CFLAGS-$(CFG_SUN50IW12P1) += -Iservice/standby/suspend_resume/mem-sun50iw12p1/
#LINK-$(CFG_SUN50IW12P1) := coco/arch/openrisc/plat-sun50iw12p1/kern.ld.S
LINK_RAM-$(CFG_SUN50IW12P1) := arch/openrisc/plat-sun50iw12p1/ram.ld

obj-$(CFG_SUN55IW3P1) += plat-sun55iw3p1/
CFLAGS-$(CFG_SUN55IW3P1) += -Iarch/openrisc/plat-sun55iw3p1/inc
CFLAGS-$(CFG_SUN55IW3P1) += -Iservice/standby/suspend_resume/mem-sun55iw3p1/
#LINK-$(CFG_SUN55IW3P1) := coco/arch/openrisc/plat-sun55iw3p1/kern.ld.S
LINK_RAM-$(CFG_SUN55IW3P1) := arch/openrisc/plat-sun55iw3p1/ram.ld

obj-$(CFG_SUN60IW1P1) += plat-sun60iw1p1/
CFLAGS-$(CFG_SUN60IW1P1) += -Iarch/openrisc/plat-sun60iw1p1/inc
CFLAGS-$(CFG_SUN60IW1P1) += -Iservice/standby/suspend_resume/mem-sun60iw1p1/
#LINK-$(CFG_SUN60IW1P1) := coco/arch/openrisc/plat-sun60iw1p1/kern.ld.S
LINK_RAM-$(CFG_SUN60IW1P1) := arch/openrisc/plat-sun60iw1p1/ram.ld
