# Copyright 2008 The Android Open Source Project
#
LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := vendor_am
LOCAL_MODULE_CLASS := JAVA_LIBRARIES
LOCAL_ENFORCE_USES_LIBRARIES := false
LOCAL_PREBUILT_MODULE_FILE := $(call intermediates-dir-for,JAVA_LIBRARIES,am)/javalib.jar
LOCAL_STRIP_MODULE := false
LOCAL_MODULE_TAGS := optional
LOCAL_INSTALLED_MODULE_STEM := vendor_am.jar
LOCAL_PROPRIETARY_MODULE := true
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := vendor_am
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_ENFORCE_USES_LIBRARIES := false
LOCAL_PREBUILT_MODULE_FILE := $(call intermediates-dir-for,EXECUTABLES,am)/am
LOCAL_STRIP_MODULE := false
LOCAL_MODULE_TAGS := optional
LOCAL_INSTALLED_MODULE_STEM := am
LOCAL_MODULE_PATH := $(TARGET_OUT_VENDOR)/xbin
LOCAL_PROPRIETARY_MODULE := true
include $(BUILD_PREBUILT)
